{{- if not .Values.haEnabled }}
# -------------------------------
# Persistent Volume Claim
# -------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "etcd.fullname" . }}-data
  namespace: {{ include "etcd.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}

---
# -------------------------------
# Etcd Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etcd.fullname" . }}
  namespace: {{ include "etcd.namespace" . }}
spec:
  replicas: {{ .Values.standaloneReplicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "etcd.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "etcd.fullname" . }}
    spec:
      containers:
        - name: etcd
          image: {{ .Values.image }}
          command:
            - etcd
            - --data-dir=/var/lib/etcd
            - --listen-client-urls=http://0.0.0.0:{{ .Values.grpcPort }}
            - --listen-client-http-urls=http://0.0.0.0:{{ .Values.httpPort }}
            - --advertise-client-urls=http://{{ include "etcd.fullname" . }}:{{ .Values.grpcPort }}
          ports:
            - name: client-grpc
              containerPort: {{ .Values.grpcPort }}
            - name: client-http
              containerPort: {{ .Values.httpPort }}
          {{- if .Values.healthChecks.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthChecks.liveness.path }}
              port: {{ .Values.httpPort }}
            initialDelaySeconds: {{ .Values.healthChecks.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthChecks.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthChecks.readiness.path }}
              port: {{ .Values.httpPort }}
            initialDelaySeconds: {{ .Values.healthChecks.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthChecks.readiness.failureThreshold }}
          startupProbe:
            httpGet:
              path: {{ .Values.healthChecks.startup.path }}
              port: {{ .Values.httpPort }}
            periodSeconds: {{ .Values.healthChecks.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.healthChecks.startup.failureThreshold }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/etcd
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "etcd.fullname" . }}-data

---
# -------------------------------
# Etcd Client Service
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  namespace: {{ include "etcd.namespace" . }}
  labels:
    app: {{ include "etcd.fullname" . }}
    etcd.service: client
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "etcd.fullname" . }}
  ports:
    - name: client-grpc
      port: {{ .Values.grpcPort }}
      targetPort: {{ .Values.grpcPort }}
    - name: client-http
      port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
{{- end }}
